### ISSUE TITLE
有遇到过加密串前+04 前端无法解密的问题吗

### ISSUE THREAD

**Issue by zhoulangchua** [JuneAndGreen/sm-crypto#35]

**Comment by zhoulangchua** [comment]
let sigValueHex6 = sm2.doSignature("这是加密123456", privateKeyWeb, {
    hash: true,
    publicKeyWeb,
    userId: '1234567812345678',
})
console.log(sigValueHex6);

let verifyResult6 = sm2.doVerifySignature("这是加密123456", sigValueHex6, publicKeyWeb, {
    hash: true,
    userId: '1234567812345678',
})

console.log(verifyResult6);





[Running] node "d:\Workspace\newProject\aggregate\tianjinfarmer\src\service\tempCodeRunnerFile.js"
acb3cb0b65a03a20a9c57eb2cdb77049ff957814828ffb9aa2a4b543a1a7aa3e5dcf01ff9bd8058658f53564be76233f43d4acb034632a74204bff9e81985946
D:\Workspace\newProject\aggregate\tianjinfarmer\node_modules\_sm-crypto@0.2.1@sm-crypto\src\sm2\index.js:154
  const x1y1 = G.multiply(s).add(PA.multiply(t))
                                    ^

TypeError: Cannot read property 'multiply' of null
    at Object.doVerifySignature (D:\Workspace\newProject\aggregate\tianjinfarmer\node_modules\_sm-crypto@0.2.1@sm-crypto\src\sm2\index.js:154:37)
    at Object.<anonymous> (d:\Workspace\newProject\aggregate\tianjinfarmer\src\service\tempCodeRunnerFile.js:32:24)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:623:3)

[Done] exited with code=1 in 0.211 seconds

[Running] node "d:\Workspace\newProject\aggregate\tianjinfarmer\src\service\tempCodeRunnerFile.js"
00236952d94b04e2ad2a240bd054016c367ee9253c194ec75e6b41116478ee93cb1b324eaeaaa900b2a516503b1476a94a51dfee4c3d72f3e663994c57b8af1b

[Done] exited with code=0 in 0.237 seconds
错误如下 ：  
[Running] node "d:\Workspace\newProject\aggregate\tianjinfarmer\src\service\tempCodeRunnerFile.js"
0897d7bf791a538f32e5d18a17f5b4578c9434800d884c89d554ebbcbded056708adb68956f3d74baa80d3d1d3e57211158b2d0960c27678ed126d45a4059cc7
D:\Workspace\newProject\aggregate\tianjinfarmer\node_modules\_sm-crypto@0.2.1@sm-crypto\src\sm2\index.js:154
  const x1y1 = G.multiply(s).add(PA.multiply(t))
                                    ^

TypeError: Cannot read property 'multiply' of null
    at Object.doVerifySignature (D:\Workspace\newProject\aggregate\tianjinfarmer\node_modules\_sm-crypto@0.2.1@sm-crypto\src\sm2\index.js:154:37)
    at Object.<anonymous> (d:\Workspace\newProject\aggregate\tianjinfarmer\src\service\tempCodeRunnerFile.js:36:25)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:623:3)


这个问题很懵啊 所有的签名都能过去 但就是 验签 过不了  都会报**  Cannot read property 'multiply' of null**

**Comment by human-user** [comment]
我也遇到了，这个手动去掉04就能解密

**Comment by XXXJing** [comment]
前端解密的时候会自己加上04， 后端传过来有04的话就得去掉才能正常解密
