### ISSUE TITLE
所有验签都失败！！！！

### ISSUE THREAD

**Issue by zhoulangchua** [JuneAndGreen/sm-crypto#36]
`let sigValueHex6 = sm2.doSignature("这是加密123456", privateKeyWeb, {
hash: true,
publicKeyWeb,
userId: '1234567812345678',
})
console.log(sigValueHex6);

let verifyResult6 = sm2.doVerifySignature("这是加密123456", sigValueHex6, publicKeyWeb, {
hash: true,
userId: '1234567812345678',
})

console.log(verifyResult6);`

错误如下 ：
[Running] node "d:\Workspace\newProject\aggregate\tianjinfarmer\src\service\tempCodeRunnerFile.js"
0897d7bf791a538f32e5d18a17f5b4578c9434800d884c89d554ebbcbded056708adb68956f3d74baa80d3d1d3e57211158b2d0960c27678ed126d45a4059cc7
D:\Workspace\newProject\aggregate\tianjinfarmer\node_modules_sm-crypto@0.2.1@sm-crypto\src\sm2\index.js:154
const x1y1 = G.multiply(s).add(PA.multiply(t))
^

TypeError: Cannot read property 'multiply' of null
at Object.doVerifySignature (D:\Workspace\newProject\aggregate\tianjinfarmer\node_modules_sm-crypto@0.2.1@sm-crypto\src\sm2\index.js:154:37)
at Object. (d:\Workspace\newProject\aggregate\tianjinfarmer\src\service\tempCodeRunnerFile.js:36:25)
at Module._compile (internal/modules/cjs/loader.js:778:30)
at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
at Module.load (internal/modules/cjs/loader.js:653:32)
at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
at Function.Module._load (internal/modules/cjs/loader.js:585:3)
at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
at startup (internal/bootstrap/node.js:283:19)
at bootstrapNodeJSCore (internal/bootstrap/node.js:623:3)

这个问题很懵啊 所有的签名都能过去 但就是 验签 过不了 都会报** Cannot read property 'multiply' of null**

**Comment by karboom** [comment]
你的公钥是如何获取到的，可能是公钥解码失败了 源代码里面的这个函数`decodePointHex`，你可以看一下
